# -*- coding: utf-8 -*-
"""metaVolume_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JyADEkpAcXlHGu3pXhRIHsizX2m1g-7Q
"""

import os
os.chdir('/content')

!apt-get install git
!git clone https://github.com/simsisim/metaVolume.git
#!git clone https://github.com/simsisim/marketScanners_v1
#!git clone https://github.com/simsisim/portofolio_signals_v1

!pwd
from google.colab import drive
drive.mount('/content/drive')
#drive.mount('/content/drive', force_remount = True)

!cp -r /content/metaVolume "/content/drive/MyDrive/_invest2024_py_run/run_python/"



import pandas as pd
print(pd.__version__)
!pip install  pandas numpy
!pip install --upgrade yfinance>=1.1.0
!pip install mplfinance
!pip install reportlab
!pip install pandas_ta
!apt-get install -y poppler-utils

!pip show yfinance

"""1. **DOWNLOAD DATA**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/_invest2024_py_run/run_python/metaVolume

"""**RUN** **SCANNERS**"""

!python main.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/_invest2024/run_python/metaData_v1

!ls -lt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/_invest2024/run_python/metaData_v1

!ls -lt /content/drive/MyDrive/_invest2024/run_python/metaData_v1

!python main.py

"""# New Section"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/_invest2024/run_python/metaData_v1